services:
  lms-data-base:
    image: postgres:15
    container_name: lms-data-base
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: NURIK2005
      POSTGRES_DB: LmsDataBase
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  go-lms-system:
    build: .
    container_name: go-lms-system
    ports:
      - "8080:8080"
    environment:
      DB_HOST: lms-data-base
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: NURIK2005
      DB_NAME: LmsDataBase
    depends_on:
      - lms-data-base
    restart: on-failure

volumes:
  postgres_data:
